import {
  DEFAULT_PREFIX,
  WEBSOCKET_MESSAGE,
  WEBSOCKET_CONNECT,
  WEBSOCKET_DISCONNECT,
} from '@giantmachines/redux-websocket';

export const WS_MESSAGE_TYPE = `${DEFAULT_PREFIX}::${WEBSOCKET_MESSAGE}`;
export const WS_CONNECT_TYPE = `${DEFAULT_PREFIX}::${WEBSOCKET_CONNECT}`;
export const WS_DISCONNECT_TYPE = `${DEFAULT_PREFIX}::${WEBSOCKET_DISCONNECT}`;
