export const RETRIEVE_LEAD = 'RETRIEVE_LEAD';
export const CREATE_LEAD = 'CREATE_LEAD';
export const UPDATE_LEAD = 'UPDATE_LEAD';

export const SEND_VALIDATION_INFO_LEAD = 'SEND_VALIDATION_INFO_LEAD';
export const SEND_VALIDATION_CRED_LEAD = 'SEND_VALIDATION_CRED_LEAD';
